name: Claude Code Action
on:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          api_key: ${{ secrets.ANTHROPIC_API_KEY }}
```

### Step 5: Commit the File
1. Scroll down to the bottom
2. You'll see a section that says "Commit new file"
3. In the message box, type something like: `Add Claude Code workflow`
4. Click **"Commit new file"** button

✅ Done! The folder and file are created!

---

## **Method 2: Create an Empty Folder (If You Need Just the Folder)**

If you need just an empty `.github/workflows/` folder without a file:

1. Click **"Add file"** → **"Create new file"**
2. Type: `.github/workflows/.gitkeep`
3. Leave the content area empty
4. Click **"Commit new file"**

This creates the folder structure without a file in it.

---

## **Visual Guide (What It Looks Like)**

After you do this, your repository will look like this:
```
Your Repository
├── .github/
│   └── workflows/
│       └── claude.yml
├── (your other files)
```

---

## **Method 3: Using Your Computer (If You Want to Use Git)**

If you already have Git installed and want to do it from your computer:

1. Open Command Prompt or Terminal
2. Go to your repository folder:
```
   cd your-repository-name
```

3. Create the folders:
```
   mkdir -p .github/workflows
```

4. Create the file inside:
```
   echo "" > .github/workflows/claude.yml
```

5. Open `claude.yml` in a text editor and paste the code
6. Save the file
7. Push to GitHub:
```
   git add .
   git commit -m "Add Claude Code workflow"
   git push
